### ISSUE TITLE
The soft db status require an adjustment.

### ISSUE THREAD

**Issue by samumaretiya** [magesuite/soft-db-status-validation#2]
public function __construct(
         \Magento\Framework\Cache\FrontendInterface $cache,
         \Magento\Framework\Module\DbVersionInfo $dbVersionInfo,
+        \Magento\Framework\App\DeploymentConfig $deploymentConfig,
         \MageSuite\SoftDbStatusValidation\Model\Config $config,
         \Magento\Framework\App\State $appState,
         \Psr\Log\LoggerInterface $logger
     ) {
-        parent::__construct($cache, $dbVersionInfo);
+        parent::__construct($cache, $dbVersionInfo,  $deploymentConfig);
 
         $this->config = $config;
         $this->logger = $logger;

**Comment by diwipl** [comment]
Hi,
This is already done in branch 2.x

**Comment by samumaretiya** [comment]
Hi Diwipl, Thanks for replying.

Could you please let me know which version of mage suite got this fixed. We are using ^10.0.0

Any quick prompt is highly appreciate. 

Thanks, sam

**Comment by diwipl** [comment]
Currently there is no version compatible with Magento 2.4.4 yet, we're working on that at the moment.

You can set v2.0.0 of this package yourself in your main composer.json by using composer aliasing.

**Comment by ggm-dev** [comment]
Hi All - I just upgraded to Magesuite v11 w/OpenSource 2.4.4-p1 and it looks like this module is stuck at v1.0, causing the error mentioned above.    Do you still recommend aliasing to v2.0 or is there a better fix?

Thanks!
David

**Comment by nilsboe** [comment]
Still an issue on MageSuite v11.0.0, Magento CE 2.4.5
`composer why creativestyle/magesuite-soft-db-status-validation
creativestyle/magesuite  v11.0.0  requires  creativestyle/magesuite-soft-db-status-validation (^1.0.0)`

**Comment by diwipl** [comment]
Hi

The composer.json for v11 of MageSuite was updated and now requires `^2.0.0`
